version: '3' 

services:
  mongo:
    image: 'mongo:6.0.4'
    expose:
      - "27017"
    volumes:
      - './data/db:/data/db'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret

  backend:
    image: 'voodoo-server'
    build: ./application/server
    environment:
      - RUST_LOG=info
    expose:
      - "8000"
    depends_on:
      - mongo

  app:
    image: 'voodoo-app'
    build: ./application/front
    ports:
      - '8000:80'
    depends_on:
      - backend
    
